version: '3.10'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ProdigiDesk
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1766
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:1766@db:5432/ProdigiDesk


volumes:
  postgres_data: 