# Generated by Django 5.0.6 on 2024-08-08 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_profile_valid_from_profile_valid_till'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_service', models.BooleanField(default=False)),
                ('offer_letter_service', models.BooleanField(default=False)),
                ('business_proposal_service', models.BooleanField(default=False)),
                ('sales_script_service', models.BooleanField(default=False)),
                ('content_generation_service', models.BooleanField(default=False)),
                ('summarize_service', models.BooleanField(default=False)),
                ('ppt_generation_service', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
