# Generated by Django 5.0.6 on 2024-08-21 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254),
            preserve_default=False,
        ),
    ]
