# Generated by Django 5.0.6 on 2024-08-25 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_usersession_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='valid_from',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='valid_till',
        ),
    ]
