# Generated by Django 5.0.6 on 2024-08-29 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_temporaryemailverificationotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userservice',
            name='business_proposal_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userservice',
            name='content_generation_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userservice',
            name='email_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userservice',
            name='offer_letter_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userservice',
            name='ppt_generation_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userservice',
            name='sales_script_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userservice',
            name='summarize_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
