# Generated by Django 5.0.6 on 2024-08-31 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_userservice_business_proposal_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userservice',
            name='blog_generation_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userservice',
            name='blog_generation_service',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userservice',
            name='rephrasely_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userservice',
            name='rephrasely_service',
            field=models.BooleanField(default=False),
        ),
    ]
