# Generated by Django 5.0.6 on 2024-09-13 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_payment_email_payment_payment_id_payment_signature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_mode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
