# Generated by Django 5.0.6 on 2024-09-13 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_payment_payment_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_mode',
        ),
    ]
