# Generated by Django 5.0.6 on 2024-09-27 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_payment_payment_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestUserLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=15)),
                ('otp', models.CharField(max_length=6)),
                ('logged_in_at', models.DateTimeField(auto_now_add=True)),
                ('valid_till', models.DateTimeField()),
            ],
        ),
    ]
