# Generated by Django 5.0.6 on 2024-09-27 05:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_guestuserlogin'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestuserlogin',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='guestuserlogin',
            name='session_id',
            field=models.CharField(default=uuid.uuid4, max_length=255, unique=True),
        ),
    ]
