# Generated by Django 5.0.6 on 2024-09-27 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_guestuserlogin_is_active_guestuserlogin_session_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GuestUserLogin',
            new_name='GuestLogin',
        ),
    ]
