# Generated by Django 5.0.6 on 2024-09-27 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_rename_guestuserlogin_guestlogin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestlogin',
            name='mobile_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
