# Generated by Django 5.0.6 on 2024-10-04 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_payment_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='service',
        ),
    ]
