# Generated by Django 5.0.6 on 2024-10-07 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
