# Generated by Django 5.0.6 on 2024-10-07 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_delete_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('email_service', models.BooleanField(default=False)),
                ('offer_letter_service', models.BooleanField(default=False)),
                ('business_proposal_service', models.BooleanField(default=False)),
                ('sales_script_service', models.BooleanField(default=False)),
                ('content_generation_service', models.BooleanField(default=False)),
                ('summarize_service', models.BooleanField(default=False)),
                ('ppt_generation_service', models.BooleanField(default=False)),
                ('blog_generation_service', models.BooleanField(default=False)),
                ('rephrasely_service', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
