# Generated by Django 5.0.6 on 2024-10-10 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_cart_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='order_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.userservice'),
        ),
        migrations.AddField(
            model_name='payment',
            name='subscribed_services',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
