# Generated by Django 5.0.6 on 2024-10-14 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_payment_order_datetime_payment_service_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestlogin',
            name='mobile_number',
        ),
        migrations.AddField(
            model_name='guestlogin',
            name='email',
            field=models.EmailField(max_length=255, null=True, unique=True),
        ),
    ]
