# Generated by Django 5.0.6 on 2024-10-14 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_remove_guestlogin_mobile_number_guestlogin_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestlogin',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
