# Generated by Django 5.0.6 on 2024-10-28 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_yearlycart_alter_guestlogin_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='invoice_number',
            field=models.CharField(editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='subscription_duration',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
