# Generated by Django 5.0.6 on 2024-11-04 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_payment_invoice_number_payment_subscription_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_gst',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
