# Generated by Django 5.0.6 on 2024-11-11 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_profile_user_gst'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestWordCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('word_count', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='guestlogin',
            name='words_count',
            field=models.IntegerField(default=0),
        ),
    ]
