# Generated by Django 5.0.6 on 2024-11-11 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_guestwordcount_guestlogin_words_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GuestWordCount',
        ),
    ]
