# Generated by Django 5.0.6 on 2024-11-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_guestwordscount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestlogin',
            name='words_count',
            field=models.IntegerField(),
        ),
    ]
