# Generated by Django 5.0.6 on 2024-11-11 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alter_guestlogin_words_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestlogin',
            name='words_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
