# Generated by Django 5.0.6 on 2024-11-11 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_alter_guestlogin_words_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestlogin',
            name='words_count',
            field=models.IntegerField(default=0),
        ),
    ]
