# Generated by Django 5.0.6 on 2024-11-12 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_alter_guestlogin_words_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestlogin',
            name='words_count',
        ),
        migrations.AddField(
            model_name='guestlogin',
            name='word_count',
            field=models.IntegerField(default=0),
        ),
    ]
