# Generated by Django 5.0.6 on 2024-11-13 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_remove_guestlogin_words_count_guestlogin_word_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestlogin',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
