# Generated by Django 5.0.6 on 2025-01-14 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_userpasswordhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPasswordHistory',
        ),
    ]
